package orderHistory.mappers;

import java.util.List;
import orderHistory.entity.Citys;
import orderHistory.entity.CitysExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CitysMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	long countByExample(CitysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByExample(CitysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByPrimaryKey(String cityCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insert(Citys row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insertSelective(Citys row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	List<Citys> selectByExample(CitysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	Citys selectByPrimaryKey(String cityCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExampleSelective(@Param("row") Citys row, @Param("example") CitysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExample(@Param("row") Citys row, @Param("example") CitysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByPrimaryKeySelective(Citys row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table citys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByPrimaryKey(Citys row);
}