package orderHistory.mappers;

import java.util.List;
import orderHistory.entity.Customers;
import orderHistory.entity.CustomersExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CustomersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	long countByExample(CustomersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByExample(CustomersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByPrimaryKey(String cusCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insert(Customers row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insertSelective(Customers row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	List<Customers> selectByExample(CustomersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	Customers selectByPrimaryKey(String cusCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExampleSelective(@Param("row") Customers row, @Param("example") CustomersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExample(@Param("row") Customers row, @Param("example") CustomersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByPrimaryKeySelective(Customers row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByPrimaryKey(Customers row);
}