package orderHistory.mappers;

import java.util.List;
import orderHistory.entity.Employees;
import orderHistory.entity.EmployeesExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmployeesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	long countByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByPrimaryKey(String empId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insert(Employees row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insertSelective(Employees row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	List<Employees> selectByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	Employees selectByPrimaryKey(String empId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExampleSelective(@Param("row") Employees row, @Param("example") EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExample(@Param("row") Employees row, @Param("example") EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByPrimaryKeySelective(Employees row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByPrimaryKey(Employees row);
}