package orderHistory.mappers;

import java.util.List;
import orderHistory.entity.EmpTitles;
import orderHistory.entity.EmpTitlesExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmpTitlesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	long countByExample(EmpTitlesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByExample(EmpTitlesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByPrimaryKey(String titleCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insert(EmpTitles row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insertSelective(EmpTitles row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	List<EmpTitles> selectByExample(EmpTitlesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	EmpTitles selectByPrimaryKey(String titleCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExampleSelective(@Param("row") EmpTitles row, @Param("example") EmpTitlesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExample(@Param("row") EmpTitles row, @Param("example") EmpTitlesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByPrimaryKeySelective(EmpTitles row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByPrimaryKey(EmpTitles row);
}