package orderHistory.mappers;

import java.util.List;
import orderHistory.entity.OrderHistorys;
import orderHistory.entity.OrderHistorysExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderHistorysMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_historys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	long countByExample(OrderHistorysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_historys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByExample(OrderHistorysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_historys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insert(OrderHistorys row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_historys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insertSelective(OrderHistorys row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_historys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	List<OrderHistorys> selectByExample(OrderHistorysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_historys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExampleSelective(@Param("row") OrderHistorys row, @Param("example") OrderHistorysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_historys
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExample(@Param("row") OrderHistorys row, @Param("example") OrderHistorysExample example);
}