package orderHistory.mappers;

import java.util.List;
import orderHistory.entity.Products;
import orderHistory.entity.ProductsExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	long countByExample(ProductsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByExample(ProductsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int deleteByPrimaryKey(String productCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insert(Products row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int insertSelective(Products row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	List<Products> selectByExample(ProductsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	Products selectByPrimaryKey(String productCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExampleSelective(@Param("row") Products row, @Param("example") ProductsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByExample(@Param("row") Products row, @Param("example") ProductsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByPrimaryKeySelective(Products row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	int updateByPrimaryKey(Products row);
}