package orderHistory.entity;

public class Areas {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column areas.area_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private Integer areaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column areas.area_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String areaName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column areas.area_code
	 * @return  the value of areas.area_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Integer getAreaCode() {
		return areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column areas.area_code
	 * @param areaCode  the value for areas.area_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setAreaCode(Integer areaCode) {
		this.areaCode = areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column areas.area_name
	 * @return  the value of areas.area_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column areas.area_name
	 * @param areaName  the value for areas.area_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}
}