package orderHistory.entity;

public class Citys {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column citys.city_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String cityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column citys.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private Integer prefectureCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column citys.city_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String cityName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column citys.city_code
	 * @return  the value of citys.city_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getCityCode() {
		return cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column citys.city_code
	 * @param cityCode  the value for citys.city_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column citys.prefecture_code
	 * @return  the value of citys.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Integer getPrefectureCode() {
		return prefectureCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column citys.prefecture_code
	 * @param prefectureCode  the value for citys.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setPrefectureCode(Integer prefectureCode) {
		this.prefectureCode = prefectureCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column citys.city_name
	 * @return  the value of citys.city_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column citys.city_name
	 * @param cityName  the value for citys.city_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}
}