package orderHistory.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CustomersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public CustomersExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andCusCodeIsNull() {
			addCriterion("cus_code is null");
			return (Criteria) this;
		}

		public Criteria andCusCodeIsNotNull() {
			addCriterion("cus_code is not null");
			return (Criteria) this;
		}

		public Criteria andCusCodeEqualTo(String value) {
			addCriterion("cus_code =", value, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeNotEqualTo(String value) {
			addCriterion("cus_code <>", value, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeGreaterThan(String value) {
			addCriterion("cus_code >", value, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeGreaterThanOrEqualTo(String value) {
			addCriterion("cus_code >=", value, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeLessThan(String value) {
			addCriterion("cus_code <", value, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeLessThanOrEqualTo(String value) {
			addCriterion("cus_code <=", value, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeLike(String value) {
			addCriterion("cus_code like", value, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeNotLike(String value) {
			addCriterion("cus_code not like", value, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeIn(List<String> values) {
			addCriterion("cus_code in", values, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeNotIn(List<String> values) {
			addCriterion("cus_code not in", values, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeBetween(String value1, String value2) {
			addCriterion("cus_code between", value1, value2, "cusCode");
			return (Criteria) this;
		}

		public Criteria andCusCodeNotBetween(String value1, String value2) {
			addCriterion("cus_code not between", value1, value2, "cusCode");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIsNull() {
			addCriterion("family_name is null");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIsNotNull() {
			addCriterion("family_name is not null");
			return (Criteria) this;
		}

		public Criteria andFamilyNameEqualTo(String value) {
			addCriterion("family_name =", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotEqualTo(String value) {
			addCriterion("family_name <>", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameGreaterThan(String value) {
			addCriterion("family_name >", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameGreaterThanOrEqualTo(String value) {
			addCriterion("family_name >=", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLessThan(String value) {
			addCriterion("family_name <", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLessThanOrEqualTo(String value) {
			addCriterion("family_name <=", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLike(String value) {
			addCriterion("family_name like", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotLike(String value) {
			addCriterion("family_name not like", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIn(List<String> values) {
			addCriterion("family_name in", values, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotIn(List<String> values) {
			addCriterion("family_name not in", values, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameBetween(String value1, String value2) {
			addCriterion("family_name between", value1, value2, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotBetween(String value1, String value2) {
			addCriterion("family_name not between", value1, value2, "familyName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNull() {
			addCriterion("first_name is null");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNotNull() {
			addCriterion("first_name is not null");
			return (Criteria) this;
		}

		public Criteria andFirstNameEqualTo(String value) {
			addCriterion("first_name =", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotEqualTo(String value) {
			addCriterion("first_name <>", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThan(String value) {
			addCriterion("first_name >", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("first_name >=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThan(String value) {
			addCriterion("first_name <", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThanOrEqualTo(String value) {
			addCriterion("first_name <=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLike(String value) {
			addCriterion("first_name like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotLike(String value) {
			addCriterion("first_name not like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIn(List<String> values) {
			addCriterion("first_name in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotIn(List<String> values) {
			addCriterion("first_name not in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameBetween(String value1, String value2) {
			addCriterion("first_name between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotBetween(String value1, String value2) {
			addCriterion("first_name not between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterionForJDBCDate("birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterionForJDBCDate("birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterionForJDBCDate("birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<Date> values) {
			addCriterionForJDBCDate("birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<Date> values) {
			addCriterionForJDBCDate("birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andGenderCodeIsNull() {
			addCriterion("gender_code is null");
			return (Criteria) this;
		}

		public Criteria andGenderCodeIsNotNull() {
			addCriterion("gender_code is not null");
			return (Criteria) this;
		}

		public Criteria andGenderCodeEqualTo(String value) {
			addCriterion("gender_code =", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeNotEqualTo(String value) {
			addCriterion("gender_code <>", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeGreaterThan(String value) {
			addCriterion("gender_code >", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeGreaterThanOrEqualTo(String value) {
			addCriterion("gender_code >=", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeLessThan(String value) {
			addCriterion("gender_code <", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeLessThanOrEqualTo(String value) {
			addCriterion("gender_code <=", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeLike(String value) {
			addCriterion("gender_code like", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeNotLike(String value) {
			addCriterion("gender_code not like", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeIn(List<String> values) {
			addCriterion("gender_code in", values, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeNotIn(List<String> values) {
			addCriterion("gender_code not in", values, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeBetween(String value1, String value2) {
			addCriterion("gender_code between", value1, value2, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeNotBetween(String value1, String value2) {
			addCriterion("gender_code not between", value1, value2, "genderCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeIsNull() {
			addCriterion("prefecture_code is null");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeIsNotNull() {
			addCriterion("prefecture_code is not null");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeEqualTo(Integer value) {
			addCriterion("prefecture_code =", value, "prefectureCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeNotEqualTo(Integer value) {
			addCriterion("prefecture_code <>", value, "prefectureCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeGreaterThan(Integer value) {
			addCriterion("prefecture_code >", value, "prefectureCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeGreaterThanOrEqualTo(Integer value) {
			addCriterion("prefecture_code >=", value, "prefectureCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeLessThan(Integer value) {
			addCriterion("prefecture_code <", value, "prefectureCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeLessThanOrEqualTo(Integer value) {
			addCriterion("prefecture_code <=", value, "prefectureCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeIn(List<Integer> values) {
			addCriterion("prefecture_code in", values, "prefectureCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeNotIn(List<Integer> values) {
			addCriterion("prefecture_code not in", values, "prefectureCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeBetween(Integer value1, Integer value2) {
			addCriterion("prefecture_code between", value1, value2, "prefectureCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureCodeNotBetween(Integer value1, Integer value2) {
			addCriterion("prefecture_code not between", value1, value2, "prefectureCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeIsNull() {
			addCriterion("city_code is null");
			return (Criteria) this;
		}

		public Criteria andCityCodeIsNotNull() {
			addCriterion("city_code is not null");
			return (Criteria) this;
		}

		public Criteria andCityCodeEqualTo(String value) {
			addCriterion("city_code =", value, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeNotEqualTo(String value) {
			addCriterion("city_code <>", value, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeGreaterThan(String value) {
			addCriterion("city_code >", value, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeGreaterThanOrEqualTo(String value) {
			addCriterion("city_code >=", value, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeLessThan(String value) {
			addCriterion("city_code <", value, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeLessThanOrEqualTo(String value) {
			addCriterion("city_code <=", value, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeLike(String value) {
			addCriterion("city_code like", value, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeNotLike(String value) {
			addCriterion("city_code not like", value, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeIn(List<String> values) {
			addCriterion("city_code in", values, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeNotIn(List<String> values) {
			addCriterion("city_code not in", values, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeBetween(String value1, String value2) {
			addCriterion("city_code between", value1, value2, "cityCode");
			return (Criteria) this;
		}

		public Criteria andCityCodeNotBetween(String value1, String value2) {
			addCriterion("city_code not between", value1, value2, "cityCode");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table customers
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customers
     *
     * @mbg.generated do_not_delete_during_merge Sun Sep 18 20:43:32 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}