package orderHistory.entity;

import java.util.Date;

public class Customers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.cus_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String cusCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.family_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String familyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.first_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.phone
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.email
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.birthday
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.gender_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String genderCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private Integer prefectureCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.city_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String cityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.address
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.cus_code
	 * @return  the value of customers.cus_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getCusCode() {
		return cusCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.cus_code
	 * @param cusCode  the value for customers.cus_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setCusCode(String cusCode) {
		this.cusCode = cusCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.family_name
	 * @return  the value of customers.family_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getFamilyName() {
		return familyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.family_name
	 * @param familyName  the value for customers.family_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setFamilyName(String familyName) {
		this.familyName = familyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.first_name
	 * @return  the value of customers.first_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.first_name
	 * @param firstName  the value for customers.first_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.phone
	 * @return  the value of customers.phone
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.phone
	 * @param phone  the value for customers.phone
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.email
	 * @return  the value of customers.email
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.email
	 * @param email  the value for customers.email
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.birthday
	 * @return  the value of customers.birthday
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.birthday
	 * @param birthday  the value for customers.birthday
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.gender_code
	 * @return  the value of customers.gender_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getGenderCode() {
		return genderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.gender_code
	 * @param genderCode  the value for customers.gender_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setGenderCode(String genderCode) {
		this.genderCode = genderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.prefecture_code
	 * @return  the value of customers.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Integer getPrefectureCode() {
		return prefectureCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.prefecture_code
	 * @param prefectureCode  the value for customers.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setPrefectureCode(Integer prefectureCode) {
		this.prefectureCode = prefectureCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.city_code
	 * @return  the value of customers.city_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getCityCode() {
		return cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.city_code
	 * @param cityCode  the value for customers.city_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.address
	 * @return  the value of customers.address
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.address
	 * @param address  the value for customers.address
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setAddress(String address) {
		this.address = address;
	}
}