package orderHistory.entity;

import java.util.ArrayList;
import java.util.List;

public class EmployeesExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public EmployeesExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andEmpIdIsNull() {
			addCriterion("emp_id is null");
			return (Criteria) this;
		}

		public Criteria andEmpIdIsNotNull() {
			addCriterion("emp_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmpIdEqualTo(String value) {
			addCriterion("emp_id =", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotEqualTo(String value) {
			addCriterion("emp_id <>", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdGreaterThan(String value) {
			addCriterion("emp_id >", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdGreaterThanOrEqualTo(String value) {
			addCriterion("emp_id >=", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLessThan(String value) {
			addCriterion("emp_id <", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLessThanOrEqualTo(String value) {
			addCriterion("emp_id <=", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLike(String value) {
			addCriterion("emp_id like", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotLike(String value) {
			addCriterion("emp_id not like", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdIn(List<String> values) {
			addCriterion("emp_id in", values, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotIn(List<String> values) {
			addCriterion("emp_id not in", values, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdBetween(String value1, String value2) {
			addCriterion("emp_id between", value1, value2, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotBetween(String value1, String value2) {
			addCriterion("emp_id not between", value1, value2, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpCodeIsNull() {
			addCriterion("emp_code is null");
			return (Criteria) this;
		}

		public Criteria andEmpCodeIsNotNull() {
			addCriterion("emp_code is not null");
			return (Criteria) this;
		}

		public Criteria andEmpCodeEqualTo(String value) {
			addCriterion("emp_code =", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeNotEqualTo(String value) {
			addCriterion("emp_code <>", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeGreaterThan(String value) {
			addCriterion("emp_code >", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeGreaterThanOrEqualTo(String value) {
			addCriterion("emp_code >=", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeLessThan(String value) {
			addCriterion("emp_code <", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeLessThanOrEqualTo(String value) {
			addCriterion("emp_code <=", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeLike(String value) {
			addCriterion("emp_code like", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeNotLike(String value) {
			addCriterion("emp_code not like", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeIn(List<String> values) {
			addCriterion("emp_code in", values, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeNotIn(List<String> values) {
			addCriterion("emp_code not in", values, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeBetween(String value1, String value2) {
			addCriterion("emp_code between", value1, value2, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeNotBetween(String value1, String value2) {
			addCriterion("emp_code not between", value1, value2, "empCode");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIsNull() {
			addCriterion("family_name is null");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIsNotNull() {
			addCriterion("family_name is not null");
			return (Criteria) this;
		}

		public Criteria andFamilyNameEqualTo(String value) {
			addCriterion("family_name =", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotEqualTo(String value) {
			addCriterion("family_name <>", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameGreaterThan(String value) {
			addCriterion("family_name >", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameGreaterThanOrEqualTo(String value) {
			addCriterion("family_name >=", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLessThan(String value) {
			addCriterion("family_name <", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLessThanOrEqualTo(String value) {
			addCriterion("family_name <=", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLike(String value) {
			addCriterion("family_name like", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotLike(String value) {
			addCriterion("family_name not like", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIn(List<String> values) {
			addCriterion("family_name in", values, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotIn(List<String> values) {
			addCriterion("family_name not in", values, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameBetween(String value1, String value2) {
			addCriterion("family_name between", value1, value2, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotBetween(String value1, String value2) {
			addCriterion("family_name not between", value1, value2, "familyName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNull() {
			addCriterion("first_name is null");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNotNull() {
			addCriterion("first_name is not null");
			return (Criteria) this;
		}

		public Criteria andFirstNameEqualTo(String value) {
			addCriterion("first_name =", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotEqualTo(String value) {
			addCriterion("first_name <>", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThan(String value) {
			addCriterion("first_name >", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("first_name >=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThan(String value) {
			addCriterion("first_name <", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThanOrEqualTo(String value) {
			addCriterion("first_name <=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLike(String value) {
			addCriterion("first_name like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotLike(String value) {
			addCriterion("first_name not like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIn(List<String> values) {
			addCriterion("first_name in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotIn(List<String> values) {
			addCriterion("first_name not in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameBetween(String value1, String value2) {
			addCriterion("first_name between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotBetween(String value1, String value2) {
			addCriterion("first_name not between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaIsNull() {
			addCriterion("family_kana is null");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaIsNotNull() {
			addCriterion("family_kana is not null");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaEqualTo(String value) {
			addCriterion("family_kana =", value, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaNotEqualTo(String value) {
			addCriterion("family_kana <>", value, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaGreaterThan(String value) {
			addCriterion("family_kana >", value, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaGreaterThanOrEqualTo(String value) {
			addCriterion("family_kana >=", value, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaLessThan(String value) {
			addCriterion("family_kana <", value, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaLessThanOrEqualTo(String value) {
			addCriterion("family_kana <=", value, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaLike(String value) {
			addCriterion("family_kana like", value, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaNotLike(String value) {
			addCriterion("family_kana not like", value, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaIn(List<String> values) {
			addCriterion("family_kana in", values, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaNotIn(List<String> values) {
			addCriterion("family_kana not in", values, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaBetween(String value1, String value2) {
			addCriterion("family_kana between", value1, value2, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFamilyKanaNotBetween(String value1, String value2) {
			addCriterion("family_kana not between", value1, value2, "familyKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaIsNull() {
			addCriterion("first_kana is null");
			return (Criteria) this;
		}

		public Criteria andFirstKanaIsNotNull() {
			addCriterion("first_kana is not null");
			return (Criteria) this;
		}

		public Criteria andFirstKanaEqualTo(String value) {
			addCriterion("first_kana =", value, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaNotEqualTo(String value) {
			addCriterion("first_kana <>", value, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaGreaterThan(String value) {
			addCriterion("first_kana >", value, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaGreaterThanOrEqualTo(String value) {
			addCriterion("first_kana >=", value, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaLessThan(String value) {
			addCriterion("first_kana <", value, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaLessThanOrEqualTo(String value) {
			addCriterion("first_kana <=", value, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaLike(String value) {
			addCriterion("first_kana like", value, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaNotLike(String value) {
			addCriterion("first_kana not like", value, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaIn(List<String> values) {
			addCriterion("first_kana in", values, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaNotIn(List<String> values) {
			addCriterion("first_kana not in", values, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaBetween(String value1, String value2) {
			addCriterion("first_kana between", value1, value2, "firstKana");
			return (Criteria) this;
		}

		public Criteria andFirstKanaNotBetween(String value1, String value2) {
			addCriterion("first_kana not between", value1, value2, "firstKana");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(String value) {
			addCriterion("birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(String value) {
			addCriterion("birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(String value) {
			addCriterion("birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
			addCriterion("birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(String value) {
			addCriterion("birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(String value) {
			addCriterion("birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<String> values) {
			addCriterion("birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<String> values) {
			addCriterion("birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(String value1, String value2) {
			addCriterion("birthday between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(String value1, String value2) {
			addCriterion("birthday not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andGenderCodeIsNull() {
			addCriterion("gender_code is null");
			return (Criteria) this;
		}

		public Criteria andGenderCodeIsNotNull() {
			addCriterion("gender_code is not null");
			return (Criteria) this;
		}

		public Criteria andGenderCodeEqualTo(String value) {
			addCriterion("gender_code =", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeNotEqualTo(String value) {
			addCriterion("gender_code <>", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeGreaterThan(String value) {
			addCriterion("gender_code >", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeGreaterThanOrEqualTo(String value) {
			addCriterion("gender_code >=", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeLessThan(String value) {
			addCriterion("gender_code <", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeLessThanOrEqualTo(String value) {
			addCriterion("gender_code <=", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeLike(String value) {
			addCriterion("gender_code like", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeNotLike(String value) {
			addCriterion("gender_code not like", value, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeIn(List<String> values) {
			addCriterion("gender_code in", values, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeNotIn(List<String> values) {
			addCriterion("gender_code not in", values, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeBetween(String value1, String value2) {
			addCriterion("gender_code between", value1, value2, "genderCode");
			return (Criteria) this;
		}

		public Criteria andGenderCodeNotBetween(String value1, String value2) {
			addCriterion("gender_code not between", value1, value2, "genderCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeIsNull() {
			addCriterion("shop_code is null");
			return (Criteria) this;
		}

		public Criteria andShopCodeIsNotNull() {
			addCriterion("shop_code is not null");
			return (Criteria) this;
		}

		public Criteria andShopCodeEqualTo(String value) {
			addCriterion("shop_code =", value, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeNotEqualTo(String value) {
			addCriterion("shop_code <>", value, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeGreaterThan(String value) {
			addCriterion("shop_code >", value, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeGreaterThanOrEqualTo(String value) {
			addCriterion("shop_code >=", value, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeLessThan(String value) {
			addCriterion("shop_code <", value, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeLessThanOrEqualTo(String value) {
			addCriterion("shop_code <=", value, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeLike(String value) {
			addCriterion("shop_code like", value, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeNotLike(String value) {
			addCriterion("shop_code not like", value, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeIn(List<String> values) {
			addCriterion("shop_code in", values, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeNotIn(List<String> values) {
			addCriterion("shop_code not in", values, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeBetween(String value1, String value2) {
			addCriterion("shop_code between", value1, value2, "shopCode");
			return (Criteria) this;
		}

		public Criteria andShopCodeNotBetween(String value1, String value2) {
			addCriterion("shop_code not between", value1, value2, "shopCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeIsNull() {
			addCriterion("title_code is null");
			return (Criteria) this;
		}

		public Criteria andTitleCodeIsNotNull() {
			addCriterion("title_code is not null");
			return (Criteria) this;
		}

		public Criteria andTitleCodeEqualTo(String value) {
			addCriterion("title_code =", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeNotEqualTo(String value) {
			addCriterion("title_code <>", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeGreaterThan(String value) {
			addCriterion("title_code >", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeGreaterThanOrEqualTo(String value) {
			addCriterion("title_code >=", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeLessThan(String value) {
			addCriterion("title_code <", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeLessThanOrEqualTo(String value) {
			addCriterion("title_code <=", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeLike(String value) {
			addCriterion("title_code like", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeNotLike(String value) {
			addCriterion("title_code not like", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeIn(List<String> values) {
			addCriterion("title_code in", values, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeNotIn(List<String> values) {
			addCriterion("title_code not in", values, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeBetween(String value1, String value2) {
			addCriterion("title_code between", value1, value2, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeNotBetween(String value1, String value2) {
			addCriterion("title_code not between", value1, value2, "titleCode");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employees
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employees
     *
     * @mbg.generated do_not_delete_during_merge Sun Sep 18 20:43:32 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}