package orderHistory.entity;

public class Employees {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.emp_id
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String empId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.emp_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String empCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.family_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String familyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.first_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.family_kana
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String familyKana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.first_kana
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String firstKana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.phone
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.email
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.birthday
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.gender_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String genderCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.shop_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String shopCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.title_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String titleCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.emp_id
	 * @return  the value of employees.emp_id
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.emp_id
	 * @param empId  the value for employees.emp_id
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setEmpId(String empId) {
		this.empId = empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.emp_code
	 * @return  the value of employees.emp_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getEmpCode() {
		return empCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.emp_code
	 * @param empCode  the value for employees.emp_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.family_name
	 * @return  the value of employees.family_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getFamilyName() {
		return familyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.family_name
	 * @param familyName  the value for employees.family_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setFamilyName(String familyName) {
		this.familyName = familyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.first_name
	 * @return  the value of employees.first_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.first_name
	 * @param firstName  the value for employees.first_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.family_kana
	 * @return  the value of employees.family_kana
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getFamilyKana() {
		return familyKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.family_kana
	 * @param familyKana  the value for employees.family_kana
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setFamilyKana(String familyKana) {
		this.familyKana = familyKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.first_kana
	 * @return  the value of employees.first_kana
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getFirstKana() {
		return firstKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.first_kana
	 * @param firstKana  the value for employees.first_kana
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setFirstKana(String firstKana) {
		this.firstKana = firstKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.phone
	 * @return  the value of employees.phone
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.phone
	 * @param phone  the value for employees.phone
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.email
	 * @return  the value of employees.email
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.email
	 * @param email  the value for employees.email
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.birthday
	 * @return  the value of employees.birthday
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.birthday
	 * @param birthday  the value for employees.birthday
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.gender_code
	 * @return  the value of employees.gender_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getGenderCode() {
		return genderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.gender_code
	 * @param genderCode  the value for employees.gender_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setGenderCode(String genderCode) {
		this.genderCode = genderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.shop_code
	 * @return  the value of employees.shop_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getShopCode() {
		return shopCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.shop_code
	 * @param shopCode  the value for employees.shop_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setShopCode(String shopCode) {
		this.shopCode = shopCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.title_code
	 * @return  the value of employees.title_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getTitleCode() {
		return titleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.title_code
	 * @param titleCode  the value for employees.title_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setTitleCode(String titleCode) {
		this.titleCode = titleCode;
	}
}