package orderHistory.entity;

public class EmpTitles {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_titles.title_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String titleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_titles.title_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String titleName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_titles.title_code
	 * @return  the value of emp_titles.title_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getTitleCode() {
		return titleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_titles.title_code
	 * @param titleCode  the value for emp_titles.title_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setTitleCode(String titleCode) {
		this.titleCode = titleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_titles.title_name
	 * @return  the value of emp_titles.title_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getTitleName() {
		return titleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_titles.title_name
	 * @param titleName  the value for emp_titles.title_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setTitleName(String titleName) {
		this.titleName = titleName;
	}
}