package orderHistory.entity;

import java.util.ArrayList;
import java.util.List;

public class EmpTitlesExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public EmpTitlesExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTitleCodeIsNull() {
			addCriterion("title_code is null");
			return (Criteria) this;
		}

		public Criteria andTitleCodeIsNotNull() {
			addCriterion("title_code is not null");
			return (Criteria) this;
		}

		public Criteria andTitleCodeEqualTo(String value) {
			addCriterion("title_code =", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeNotEqualTo(String value) {
			addCriterion("title_code <>", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeGreaterThan(String value) {
			addCriterion("title_code >", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeGreaterThanOrEqualTo(String value) {
			addCriterion("title_code >=", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeLessThan(String value) {
			addCriterion("title_code <", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeLessThanOrEqualTo(String value) {
			addCriterion("title_code <=", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeLike(String value) {
			addCriterion("title_code like", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeNotLike(String value) {
			addCriterion("title_code not like", value, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeIn(List<String> values) {
			addCriterion("title_code in", values, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeNotIn(List<String> values) {
			addCriterion("title_code not in", values, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeBetween(String value1, String value2) {
			addCriterion("title_code between", value1, value2, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleCodeNotBetween(String value1, String value2) {
			addCriterion("title_code not between", value1, value2, "titleCode");
			return (Criteria) this;
		}

		public Criteria andTitleNameIsNull() {
			addCriterion("title_name is null");
			return (Criteria) this;
		}

		public Criteria andTitleNameIsNotNull() {
			addCriterion("title_name is not null");
			return (Criteria) this;
		}

		public Criteria andTitleNameEqualTo(String value) {
			addCriterion("title_name =", value, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameNotEqualTo(String value) {
			addCriterion("title_name <>", value, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameGreaterThan(String value) {
			addCriterion("title_name >", value, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameGreaterThanOrEqualTo(String value) {
			addCriterion("title_name >=", value, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameLessThan(String value) {
			addCriterion("title_name <", value, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameLessThanOrEqualTo(String value) {
			addCriterion("title_name <=", value, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameLike(String value) {
			addCriterion("title_name like", value, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameNotLike(String value) {
			addCriterion("title_name not like", value, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameIn(List<String> values) {
			addCriterion("title_name in", values, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameNotIn(List<String> values) {
			addCriterion("title_name not in", values, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameBetween(String value1, String value2) {
			addCriterion("title_name between", value1, value2, "titleName");
			return (Criteria) this;
		}

		public Criteria andTitleNameNotBetween(String value1, String value2) {
			addCriterion("title_name not between", value1, value2, "titleName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table emp_titles
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table emp_titles
     *
     * @mbg.generated do_not_delete_during_merge Sun Sep 18 20:43:32 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}