package orderHistory.entity;

public class Prefectures {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private Integer prefectureCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.prefecture_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String prefectureName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column prefectures.area_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private Integer areaCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.prefecture_code
	 * @return  the value of prefectures.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Integer getPrefectureCode() {
		return prefectureCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.prefecture_code
	 * @param prefectureCode  the value for prefectures.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setPrefectureCode(Integer prefectureCode) {
		this.prefectureCode = prefectureCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.prefecture_name
	 * @return  the value of prefectures.prefecture_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getPrefectureName() {
		return prefectureName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.prefecture_name
	 * @param prefectureName  the value for prefectures.prefecture_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setPrefectureName(String prefectureName) {
		this.prefectureName = prefectureName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prefectures.area_code
	 * @return  the value of prefectures.area_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Integer getAreaCode() {
		return areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prefectures.area_code
	 * @param areaCode  the value for prefectures.area_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setAreaCode(Integer areaCode) {
		this.areaCode = areaCode;
	}
}