package orderHistory.entity;

public class Shops {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.shop_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String shopCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.shop_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private String shopName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	private Integer prefectureCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.shop_code
	 * @return  the value of shops.shop_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getShopCode() {
		return shopCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.shop_code
	 * @param shopCode  the value for shops.shop_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setShopCode(String shopCode) {
		this.shopCode = shopCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.shop_name
	 * @return  the value of shops.shop_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.shop_name
	 * @param shopName  the value for shops.shop_name
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.prefecture_code
	 * @return  the value of shops.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public Integer getPrefectureCode() {
		return prefectureCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.prefecture_code
	 * @param prefectureCode  the value for shops.prefecture_code
	 * @mbg.generated  Sat Sep 14 06:48:47 JST 2024
	 */
	public void setPrefectureCode(Integer prefectureCode) {
		this.prefectureCode = prefectureCode;
	}
}